apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: the-last-straw-app
spec:
  # type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  type: NodePort
