apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: the-last-straw-app
spec:
  # type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: NodePort
