apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: the-last-straw-app
spec:
  type: ClusterIP  # Use NodePort or LoadBalancer if you need external access
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
